const BINANCE_API_KEY = "UHHrakmWxGjMYiXWAWGd7JA8bOsEo9pBtocP5qztGBu57UzLh2m3bhnR6j2Kfj9q";
const BINANCE_SECRET_KEY = "LIHdjCwsTUZdKQaQAOiq4pDwMcnGaQ21VzJMt10SYnw00mO57hdaJZWkbTXKvavs";

module.exports = {
    BINANCE_API_KEY,
    BINANCE_SECRET_KEY
}